device.android.name=emulator-5554
app.android.path=src/main/resources/org.wikipedia_50591.apk
app.android.package=org.wikipedia
app.android.activity=org.wikipedia.main.MainActivity
run.ip=127.0.0.1
run.port=4723
run.hybrid=false
no.reset=false

app.ios.path=/resources/wikipediaIos.app
device.ios.name=iPhone Xr
platform.ios.version=12.0